server.port=8091
spring.security.oauth2.client.registration.api-gateway.client-id=api-gateway-client
spring.security.oauth2.client.registration.api-gateway.client-secret=fjCe6ERM84QziMDNt4ZLrf3YHtpP3tQp
spring.security.oauth2.client.registration.api-gateway.scope=openid
spring.security.oauth2.client.registration.api-gateway.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.api-gateway.provider=keycloak
spring.security.oauth2.client.registration.api-gateway.redirect-uri=http://localhost:8091/login/oauth2/code/api-gateway
logging.level.org.springframework.security=DEBUG
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8080/realms/authentification/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8080/realms/authentification/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://localhost:8080/realms/authentification/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/authentification