spring.application.name=Authentification
spring.datasource.url=jdbc:mysql://localhost:3306/Test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect

### JPA / HIBERNATE ###

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.mvc.format.date=dd/MM/yyyy
server.port=8088
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


keycloak.realm=Authentification
keycloak.auth-server-url=http://localhost:8080/
keycloak.resource=User
keycloak.credentials.secret=SayVv1pugTVMJP2XxU80oC51cKAHDvBv
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/authentification
