spring.application.name=Paiment
spring.datasource.url=jdbc:mysql://localhost:3306/PaimentGestion?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8086
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#eureka server configuration
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


<<<<<<< HEAD
paypal.client.id=AamGduoRCpUnW2xYFY2hDktL8-mMj8U95a8YMO3cdO__vicrM3NVXm7P3mlik38Caocm1ORpVARLvNR0
paypal.client.secret=EDTLUkzFl6usdFvZCqSnRQaRWtLkYwhUzOnTya03o3TMWI2gtE0CsqfjpYUp6HeqrRyxKSGr6yvXBqhO
=======
paypal.client.id=AbcdEfGh123456
paypal.client.secret=xyz987SecretKEY
>>>>>>> ac0fd6d813d7f485f335f18847b9e07b523de451
paypal.base.url=https://api.sandbox.paypal.com