version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-commande
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: newGestion
    ports:
      - "3307:3306"  # Port hôte : port conteneur
    networks:
      - commande-network

  commande-gestion:
    build: .
    container_name: ms-commande
    depends_on:
      - mysql
    ports:
      - "8088:8087"  # Port hôte : port conteneur
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/newGestion
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    networks:
      - commande-network

networks:
  commande-network:
    driver: bridge
