spring.application.name=eureka
server.port=8761
eureka.client.register-with-eureka=false
<<<<<<< HEAD
eureka.client.fetch-registry=false
=======
eureka.client.fetch-registry=false
>>>>>>> ac0fd6d813d7f485f335f18847b9e07b523de451
