spring.application.name=UserGestion
<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/userGestion?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8085
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#eureka server configuration
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
=======
<<<<<<< HEAD

# Docker : remplacer localhost par le nom du service Docker (ex: mysql-user)
spring.datasource.url=jdbc:mysql://mysql-user:3306/userGestion?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8085

# Eureka
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# Config server (si nécessaire pour le microservice)
spring.cloud.config.enabled=true
spring.config.import=configserver:http://config-server:8888

# Logs
=======
spring.datasource.url=jdbc:mysql://localhost:3306/userGestion?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
 spring.datasource.username=root
 spring.datasource.password=
 spring.jpa.show-sql=true
 spring.jpa.hibernate.ddl-auto=update
 server.port=8085
 spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
 eureka server configuration
 eureka.client.register-with-eureka=true
 eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.config.enabled=true
spring.config.import=configserver:http://localhost:8888
>>>>>>> 8ff1c9f5278890ea14a0578bae16907457fbe733
logging.level.org.springframework=DEBUG
>>>>>>> ac0fd6d813d7f485f335f18847b9e07b523de451
